// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_service.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PDataEncoding int32

const (
	PDataEncoding_JSON_DEFAULT PDataEncoding = 0
	PDataEncoding_JSON_STRING  PDataEncoding = 1
	PDataEncoding_JSON_GZIP    PDataEncoding = 2
)

var PDataEncoding_name = map[int32]string{
	0: "JSON_DEFAULT",
	1: "JSON_STRING",
	2: "JSON_GZIP",
}

var PDataEncoding_value = map[string]int32{
	"JSON_DEFAULT": 0,
	"JSON_STRING":  1,
	"JSON_GZIP":    2,
}

func (x PDataEncoding) String() string {
	return proto.EnumName(PDataEncoding_name, int32(x))
}

func (PDataEncoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dac1f622be3e5824, []int{0}
}

type PApiAuth struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PApiAuth) Reset()         { *m = PApiAuth{} }
func (m *PApiAuth) String() string { return proto.CompactTextString(m) }
func (*PApiAuth) ProtoMessage()    {}
func (*PApiAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac1f622be3e5824, []int{0}
}

func (m *PApiAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PApiAuth.Unmarshal(m, b)
}
func (m *PApiAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PApiAuth.Marshal(b, m, deterministic)
}
func (m *PApiAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PApiAuth.Merge(m, src)
}
func (m *PApiAuth) XXX_Size() int {
	return xxx_messageInfo_PApiAuth.Size(m)
}
func (m *PApiAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_PApiAuth.DiscardUnknown(m)
}

var xxx_messageInfo_PApiAuth proto.InternalMessageInfo

func (m *PApiAuth) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PApiAuth) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type PApiParams struct {
	Encoding               PDataEncoding `protobuf:"varint,1,opt,name=encoding,proto3,enum=PDataEncoding" json:"encoding,omitempty"`
	ParamsData             []byte        `protobuf:"bytes,2,opt,name=paramsData,proto3" json:"paramsData,omitempty"`
	ExpectedReturnEncoding PDataEncoding `protobuf:"varint,3,opt,name=expectedReturnEncoding,proto3,enum=PDataEncoding" json:"expectedReturnEncoding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}      `json:"-"`
	XXX_unrecognized       []byte        `json:"-"`
	XXX_sizecache          int32         `json:"-"`
}

func (m *PApiParams) Reset()         { *m = PApiParams{} }
func (m *PApiParams) String() string { return proto.CompactTextString(m) }
func (*PApiParams) ProtoMessage()    {}
func (*PApiParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac1f622be3e5824, []int{1}
}

func (m *PApiParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PApiParams.Unmarshal(m, b)
}
func (m *PApiParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PApiParams.Marshal(b, m, deterministic)
}
func (m *PApiParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PApiParams.Merge(m, src)
}
func (m *PApiParams) XXX_Size() int {
	return xxx_messageInfo_PApiParams.Size(m)
}
func (m *PApiParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PApiParams.DiscardUnknown(m)
}

var xxx_messageInfo_PApiParams proto.InternalMessageInfo

func (m *PApiParams) GetEncoding() PDataEncoding {
	if m != nil {
		return m.Encoding
	}
	return PDataEncoding_JSON_DEFAULT
}

func (m *PApiParams) GetParamsData() []byte {
	if m != nil {
		return m.ParamsData
	}
	return nil
}

func (m *PApiParams) GetExpectedReturnEncoding() PDataEncoding {
	if m != nil {
		return m.ExpectedReturnEncoding
	}
	return PDataEncoding_JSON_DEFAULT
}

type PApiResult struct {
	Status               int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Encoding             PDataEncoding `protobuf:"varint,3,opt,name=encoding,proto3,enum=PDataEncoding" json:"encoding,omitempty"`
	ResultData           []byte        `protobuf:"bytes,4,opt,name=resultData,proto3" json:"resultData,omitempty"`
	DebugData            []byte        `protobuf:"bytes,5,opt,name=debugData,proto3" json:"debugData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PApiResult) Reset()         { *m = PApiResult{} }
func (m *PApiResult) String() string { return proto.CompactTextString(m) }
func (*PApiResult) ProtoMessage()    {}
func (*PApiResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac1f622be3e5824, []int{2}
}

func (m *PApiResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PApiResult.Unmarshal(m, b)
}
func (m *PApiResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PApiResult.Marshal(b, m, deterministic)
}
func (m *PApiResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PApiResult.Merge(m, src)
}
func (m *PApiResult) XXX_Size() int {
	return xxx_messageInfo_PApiResult.Size(m)
}
func (m *PApiResult) XXX_DiscardUnknown() {
	xxx_messageInfo_PApiResult.DiscardUnknown(m)
}

var xxx_messageInfo_PApiResult proto.InternalMessageInfo

func (m *PApiResult) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PApiResult) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PApiResult) GetEncoding() PDataEncoding {
	if m != nil {
		return m.Encoding
	}
	return PDataEncoding_JSON_DEFAULT
}

func (m *PApiResult) GetResultData() []byte {
	if m != nil {
		return m.ResultData
	}
	return nil
}

func (m *PApiResult) GetDebugData() []byte {
	if m != nil {
		return m.DebugData
	}
	return nil
}

type PApiContext struct {
	ApiName              string      `protobuf:"bytes,1,opt,name=apiName,proto3" json:"apiName,omitempty"`
	ApiAuth              *PApiAuth   `protobuf:"bytes,2,opt,name=apiAuth,proto3" json:"apiAuth,omitempty"`
	ApiParams            *PApiParams `protobuf:"bytes,3,opt,name=apiParams,proto3" json:"apiParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PApiContext) Reset()         { *m = PApiContext{} }
func (m *PApiContext) String() string { return proto.CompactTextString(m) }
func (*PApiContext) ProtoMessage()    {}
func (*PApiContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_dac1f622be3e5824, []int{3}
}

func (m *PApiContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PApiContext.Unmarshal(m, b)
}
func (m *PApiContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PApiContext.Marshal(b, m, deterministic)
}
func (m *PApiContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PApiContext.Merge(m, src)
}
func (m *PApiContext) XXX_Size() int {
	return xxx_messageInfo_PApiContext.Size(m)
}
func (m *PApiContext) XXX_DiscardUnknown() {
	xxx_messageInfo_PApiContext.DiscardUnknown(m)
}

var xxx_messageInfo_PApiContext proto.InternalMessageInfo

func (m *PApiContext) GetApiName() string {
	if m != nil {
		return m.ApiName
	}
	return ""
}

func (m *PApiContext) GetApiAuth() *PApiAuth {
	if m != nil {
		return m.ApiAuth
	}
	return nil
}

func (m *PApiContext) GetApiParams() *PApiParams {
	if m != nil {
		return m.ApiParams
	}
	return nil
}

func init() {
	proto.RegisterEnum("PDataEncoding", PDataEncoding_name, PDataEncoding_value)
	proto.RegisterType((*PApiAuth)(nil), "PApiAuth")
	proto.RegisterType((*PApiParams)(nil), "PApiParams")
	proto.RegisterType((*PApiResult)(nil), "PApiResult")
	proto.RegisterType((*PApiContext)(nil), "PApiContext")
}

func init() { proto.RegisterFile("api_service.proto", fileDescriptor_dac1f622be3e5824) }

var fileDescriptor_dac1f622be3e5824 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x14, 0xc4, 0x6d, 0x52, 0xe2, 0xe7, 0xb4, 0x84, 0x27, 0x14, 0x45, 0x01, 0x41, 0x09, 0x17, 0xe8,
	0x61, 0x2b, 0x05, 0x89, 0x7b, 0x4a, 0xd3, 0x12, 0x84, 0x42, 0xb4, 0x09, 0x97, 0x5e, 0xaa, 0xcd,
	0xe6, 0xe1, 0x5a, 0x4d, 0xec, 0x95, 0x77, 0x0d, 0xe5, 0x13, 0xf8, 0x0b, 0x8e, 0x7c, 0x26, 0xf2,
	0xb3, 0x8d, 0x13, 0x89, 0x8a, 0xe3, 0xcc, 0x6c, 0x26, 0x33, 0x9e, 0x07, 0x8f, 0x95, 0x89, 0xae,
	0x2d, 0xa5, 0xdf, 0x22, 0x4d, 0xc2, 0xa4, 0x89, 0x4b, 0xfa, 0x4f, 0xc3, 0x24, 0x09, 0xd7, 0x74,
	0xca, 0x68, 0x99, 0x7d, 0x3d, 0xa5, 0x8d, 0x71, 0x3f, 0x0a, 0x71, 0x70, 0x06, 0xad, 0xd9, 0xc8,
	0x44, 0xa3, 0xcc, 0xdd, 0xe0, 0x13, 0x68, 0x2a, 0x63, 0x26, 0xab, 0x9e, 0x77, 0xec, 0xbd, 0xf6,
	0x65, 0x01, 0xf0, 0x18, 0x02, 0xa5, 0x35, 0x59, 0xbb, 0x48, 0x6e, 0x29, 0xee, 0xed, 0xb1, 0xb6,
	0x4d, 0x0d, 0x7e, 0x79, 0x00, 0xb9, 0xc9, 0x4c, 0xa5, 0x6a, 0x63, 0xf1, 0x04, 0x5a, 0x14, 0xeb,
	0x64, 0x15, 0xc5, 0x21, 0x3b, 0x1d, 0x0d, 0x8f, 0xc4, 0xec, 0x5c, 0x39, 0x35, 0x2e, 0x59, 0xf9,
	0x57, 0xc7, 0xe7, 0x00, 0x86, 0x7f, 0x95, 0xeb, 0xec, 0xdd, 0x96, 0x5b, 0x0c, 0x5e, 0x40, 0x97,
	0xee, 0x0c, 0x69, 0x47, 0x2b, 0x49, 0x2e, 0x4b, 0xe3, 0xca, 0xa3, 0xb7, 0xff, 0x4f, 0xe7, 0x7b,
	0x5e, 0x0f, 0x7e, 0x97, 0x11, 0x25, 0xd9, 0x6c, 0xed, 0xb0, 0x0b, 0x07, 0xd6, 0x29, 0x97, 0x59,
	0x0e, 0xd8, 0x94, 0x25, 0xc2, 0x1e, 0x3c, 0xdc, 0x90, 0xb5, 0x2a, 0xa4, 0xb2, 0x67, 0x05, 0x77,
	0x4a, 0xed, 0xff, 0xbf, 0x54, 0xca, 0xff, 0xc3, 0xa5, 0x1a, 0x45, 0xa9, 0x9a, 0xc1, 0x67, 0xe0,
	0xaf, 0x68, 0x99, 0x85, 0x2c, 0x37, 0x59, 0xae, 0x89, 0xc1, 0x77, 0x08, 0xf2, 0xa4, 0xef, 0x93,
	0xd8, 0xd1, 0x9d, 0xcb, 0x23, 0x29, 0x13, 0x4d, 0xd5, 0x86, 0xca, 0x59, 0x2a, 0x88, 0xaf, 0x58,
	0xc9, 0x97, 0xe3, 0xb0, 0xc1, 0xd0, 0x17, 0xd5, 0x94, 0xb2, 0x52, 0xf0, 0x0d, 0xf8, 0xaa, 0x5a,
	0x86, 0x83, 0x07, 0xc3, 0x40, 0xd4, 0x63, 0xc9, 0x5a, 0x3d, 0x19, 0xc1, 0xe1, 0x4e, 0x23, 0xec,
	0x40, 0xfb, 0xe3, 0xfc, 0xf3, 0xf4, 0xfa, 0x7c, 0x7c, 0x31, 0xfa, 0xf2, 0x69, 0xd1, 0x79, 0x80,
	0x8f, 0x20, 0x60, 0x66, 0xbe, 0x90, 0x93, 0xe9, 0x65, 0xc7, 0xc3, 0x43, 0xf0, 0x99, 0xb8, 0xbc,
	0x9a, 0xcc, 0x3a, 0x7b, 0xc3, 0x9f, 0x5e, 0x11, 0x7e, 0x5e, 0x1c, 0x20, 0xbe, 0x83, 0x86, 0xc9,
	0x9d, 0xba, 0xa2, 0xb8, 0x41, 0x51, 0xdd, 0xa0, 0x18, 0xe7, 0x37, 0xd8, 0xbf, 0x87, 0xc7, 0x17,
	0xd0, 0xd4, 0x37, 0xa4, 0x6f, 0xb1, 0xae, 0xd4, 0x2f, 0x62, 0x97, 0x03, 0xbe, 0x84, 0x86, 0x56,
	0xeb, 0x35, 0xb6, 0xc5, 0xd6, 0xb7, 0xda, 0x79, 0x72, 0xd6, 0xfa, 0xe0, 0x5d, 0x35, 0xc2, 0xd4,
	0xe8, 0xe5, 0x01, 0xbb, 0xbf, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x5f, 0x1a, 0x3f, 0x1c,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PApiServiceClient is the client API for PApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PApiServiceClient interface {
	//*
	// This method is to test if server is online.
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	//*
	// This method is to test if server is online.
	Check(ctx context.Context, in *PApiAuth, opts ...grpc.CallOption) (*PApiResult, error)
	//*
	// Invoke API call.
	Call(ctx context.Context, in *PApiContext, opts ...grpc.CallOption) (*PApiResult, error)
}

type pApiServiceClient struct {
	cc *grpc.ClientConn
}

func NewPApiServiceClient(cc *grpc.ClientConn) PApiServiceClient {
	return &pApiServiceClient{cc}
}

func (c *pApiServiceClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/PApiService/ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pApiServiceClient) Check(ctx context.Context, in *PApiAuth, opts ...grpc.CallOption) (*PApiResult, error) {
	out := new(PApiResult)
	err := c.cc.Invoke(ctx, "/PApiService/check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pApiServiceClient) Call(ctx context.Context, in *PApiContext, opts ...grpc.CallOption) (*PApiResult, error) {
	out := new(PApiResult)
	err := c.cc.Invoke(ctx, "/PApiService/call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PApiServiceServer is the server API for PApiService service.
type PApiServiceServer interface {
	//*
	// This method is to test if server is online.
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	//*
	// This method is to test if server is online.
	Check(context.Context, *PApiAuth) (*PApiResult, error)
	//*
	// Invoke API call.
	Call(context.Context, *PApiContext) (*PApiResult, error)
}

// UnimplementedPApiServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPApiServiceServer struct {
}

func (*UnimplementedPApiServiceServer) Ping(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedPApiServiceServer) Check(ctx context.Context, req *PApiAuth) (*PApiResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedPApiServiceServer) Call(ctx context.Context, req *PApiContext) (*PApiResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}

func RegisterPApiServiceServer(s *grpc.Server, srv PApiServiceServer) {
	s.RegisterService(&_PApiService_serviceDesc, srv)
}

func _PApiService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PApiServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PApiService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PApiServiceServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PApiService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PApiAuth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PApiServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PApiService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PApiServiceServer).Check(ctx, req.(*PApiAuth))
	}
	return interceptor(ctx, in, info, handler)
}

func _PApiService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PApiContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PApiServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PApiService/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PApiServiceServer).Call(ctx, req.(*PApiContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _PApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PApiService",
	HandlerType: (*PApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _PApiService_Ping_Handler,
		},
		{
			MethodName: "check",
			Handler:    _PApiService_Check_Handler,
		},
		{
			MethodName: "call",
			Handler:    _PApiService_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_service.proto",
}
